spring:
  application:
    name: zuul-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    catalog:
      path: /catalog/**
      serviceId: product-catalog-service
    order:
      path: /order/**
      serviceId: product-order-service